apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app:  mysql-pod
spec:
  containers:
    - name: mysql
      image: mysql:5.6
      env:
      - name: MYSQL_ROOT_PASSWORD
      ports:
      - containerPort: 3306
  